---
title: "data_vizualization"
author: "Jonas Schaarp"
date: "6/17/2021"
output: html_document
---


```{r setup, include=FALSE}
# loading the packages
source(here::here("R/package-loading.R"))

#load the tidyed dataset
load(here::here("data/nhanes_small.rda"))
```

# One variable plots
```{r continous-variables}
#Density plot
ggplot(nhanes_small, aes( x = bmi)) + 
    geom_density()

#histogram

ggplot(nhanes_small, aes(x = bmi)) +
    geom_histogram()

```
```{r discrete-variables}
ggplot(nhanes_small, aes (x = sex)) +
    geom_bar()

ggplot(nhanes_small, aes(x = diabetes)) +
    geom_bar()
```

```{r remove-missing-diabetes}

nhanes_tidied <- nhanes_small %>% 
    filter(!is.na(diabetes))

# Safe the new dataframe overwrite is the old data set
usethis::use_data(nhanes_tidied, overwrite = T)

ggplot(nhanes_tidied, aes(x= diabetes))+
    geom_bar()
```

# Plotting two variables

```{r 2-contious-variables}
bmi_chol <- ggplot(nhanes_tidied, aes (x = bmi, y = tot_chol))

# doing a scatter plot
bmi_chol+
    geom_point()

bmi_chol+
    geom_hex()

bmi_chol+
    geom_smooth()

bmi_chol +
    geom_hex()+
    geom_smooth()
```

```{r 2-discrete-variables}

# With diabetes as the x-axis and the categorical amount distributed in sex
two_discrete <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = sex))

two_discrete+
    geom_bar()

# Further separation
two_discrete + 
    geom_bar(position = position_dodge())
```

```{r discrete-continous-variables}

two_mixed <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, y = bmi))

two_mixed+
    geom_boxplot()

two_mixed+
    geom_jitter()

two_mixed + 
    geom_violin()
```


# Exercise 11.5

```{r}
# 1a. Distribution of age
ggplot(nhanes_tidied, aes(x = age)) +
    geom_histogram(bin=30)
    
# 1b. Distribution of age of diabetes diagnosis
ggplot(nhanes_tidied, aes(x = diabetes_age)) +
    geom_histogram(bins=30)

# 2a. Number of people who smoke now
ggplot(nhanes_tidied, aes(x = smoke_now)) +
    geom_bar()

# 2b. Number of people who are physically active
ggplot(nhanes_tidied, aes(x = phys_active)) +
    geom_bar()

# 3a. BMI in relation to systolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_sys_ave)) +
    geom_hex()

# 3b. BMI relation to diastolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_dia_ave)) +
    geom_hex()
    
# 4. Physically active people with or without diabetes
ggplot(nhanes_tidied, aes(x = diabetes, fill = phys_active)) +
    geom_bar(position = position_dodge())

# 5. Poverty levels between those with or without diabetes
ggplot(nhanes_tidied, aes(x = diabetes, y = poverty)) +
    geom_violin()
```

# Plotting three or more variables
```{r using-colour}

# 1 continous and two discrite variables
nhanes_tidied %>% 
    ggplot(aes(x = sex, y = bp_sys_ave, colour = diabetes))+
    geom_boxplot()

# 3 continous variables
nhanes_tidied %>% 
    ggplot( aes(x = bmi, y = bp_sys_ave, colour= age)) +
    geom_point()

# 2 continous and 1 discrete variable
nhanes_tidied %>% 
    ggplot(aes( x = bmi, y = bp_sys_ave, colour= diabetes))+
    geom_point()

```

```{r using-faceting}
# Side-by side
nhanes_tidied %>% 
    ggplot(aes( x = bmi, y= bp_sys_ave))+
    geom_point()+
    facet_grid(cols = vars(diabetes))

# stacked
nhanes_tidied %>% 
    ggplot(aes( x = bmi, y= bp_sys_ave))+
    geom_point()+
    facet_grid(rows = vars(diabetes))

# 5-variables
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour= age))+
    geom_point()+
    facet_grid(rows = vars(diabetes), cols = vars(sex))


```
# Changing the colours

```{r}
# Barplot to work from, with two discrete variables
base_barplot <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = sex)) +
    geom_bar(position = position_dodge())
base_barplot

base_barplot + 
    scale_fill_viridis_d(option = "H")

# Scatterplot to work from, with three continuous variables
base_scatterplot <- nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point()

base_scatterplot +
    scale_color_viridis_c(option = "magma")
```
# changing plot appearence

```{r built-in-themes}
# Create scatterplot to play with themes
base_scatterplot2 <- base_scatterplot +
    facet_grid(rows = vars(diabetes),
               cols = vars(sex)) +
    scale_color_viridis_c()

# View the plot with the default theme
base_scatterplot2

#Try different theme
base_scatterplot2+
    theme_bw()
# set the theme for all plots
theme_set(theme_bw())
# chngeing 
base_scatterplot2+ labs(title = "BMI, systolic blood pressure (mmHg)", y = " sytolic blood pressure", x = "BMI kg/~m^2")
```
# saving teh plot
```{r}

ggsave(here::here("doc/images/scatterplot.pdf"),base_scatterplot2, width = 7, height = 5)
```


